### ISSUE TITLE
Could not pass event InventoryClickEvent to QABattlePass v2.4.4

### ISSUE THREAD

**Issue by Webman97** [GhostSkill/BattlePass#4]
When clicking on inventory items after using `/battlepass`, the following is thrown to console: https://pastebin.com/F21kyG8s

This has been reported in issue https://github.com/GhostSkill/BattlePass/issues/1. @GhostSkill please review and resolve.

**Comment by Webman97** [comment]
Developer has opted to revoke my access to download this plugin after ignoring my issues once I left a negative review. I will not assist further, closing.

**Comment by GhostSkill** [comment]
I didn't remove access to anything, you did chargeback, spigot took it off.

**Comment by Webman97** [comment]
@GhostSkill You've violated your own Terms and Conditions by ignoring my requests for support!! Now you listen when a chargeback occurs? Disgusting, I want no part of this! Provide the refund!

**Comment by GhostSkill** [comment]
I will refund it try and PayPal gives me error, when you let me have your money back.
